services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  web:
    build: ./web-app
    container_name: web-app
    ports:
      - "5002:5000" # Web Flask runs on port 5000
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongodb
    volumes:
      - ./web-app:/app
    env_file:
      - .env

  ml-client:
    build: ./machine-learning-client
    container_name: ml-client
    ports:
      - "5001:5001" # Expose ML API to localhost:5001
    depends_on:
      - mongodb
    volumes:
      - ./machine-learning-client:/app

volumes:
  mongo_data:
