FROM python:3.10-slim

# Set working directory inside the container
WORKDIR /app

# Copy Pipenv files
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pip install pipenv && pipenv install --system --deploy

# Copy app code
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Run the Flask app
CMD ["python", "app.py"]
