name: Machine Learning Client CI
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # repeat same job for each subsystem in the following subdirectories
        subdir: [machine-learning-client]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Update version as needed
      - name: Install dependencies
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pylint black  # Install pylint and black

      - name: Lint with pylint
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          pylint **/*.py
      - name: Format with black
        if: ${{ hashFiles('machine-learning-client/**/*.py') != '' }}
        run: |
          cd machine-learning-client
          black --diff --check .