name: Web App CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Python, pipenv and Pipfile packages
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint flask  # Install pylint and flask
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pymongo dotenv

      - name: Run Tests
        working-directory: ./web-app
        run: |
          pytest